name: Atualizar calendário de mudanças

on:
  schedule:
    - cron: '* * * * *'  # Executa a cada 1 minuto
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script Python
        env:
          JIRA_USER_EMAIL: herbert.branco@stf.jus.br
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: python main.py

      - name: Comitar e enviar alterações
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase
          git add index.html
          git commit -m "Atualização automática do calendário" || echo "Nada para commitar"
          git push
